import type { Metadata, Viewport } from 'next'
import { Inter, Geist_Mono } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import Script from 'next/script'
import './globals.css'

const _inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const _geistMono = Geist_Mono({ subsets: ['latin'] })

const SITE_URL = 'https://voltex.devlune.in'
const SITE_NAME = 'Voltex Notes'
const SITE_DESCRIPTION =
  'Open-source knowledge base with real-time cloud sync, bidirectional linking, graph view, Markdown editing, version history, and a plugin ecosystem. Built by DevLune Studios.'

export const metadata: Metadata = {
  // ─── Core ───────────────────────────────────────────────
  title: {
    default: 'Voltex Notes — Open-Source Knowledge Base with Graph View & Cloud Sync',
    template: '%s | Voltex Notes',
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  generator: 'Next.js',
  referrer: 'origin-when-cross-origin',

  // ─── Discovery ──────────────────────────────────────────
  keywords: [
    'voltex notes', 'knowledge base', 'note taking app', 'markdown editor',
    'graph view', 'bidirectional linking', 'wikilinks', 'cloud sync',
    'open source notes', 'obsidian alternative', 'personal wiki',
    'zettelkasten', 'pkm', 'second brain', 'networked thought',
    'plugin ecosystem', 'canvas view', 'excalidraw', 'version history',
    'devlune', 'devlune studios',
  ],

  // ─── Attribution ────────────────────────────────────────
  authors: [
    { name: 'Sidharth', url: 'https://devlune.in' },
    { name: 'DevLune Studios', url: 'https://devlune.in' },
  ],
  creator: 'DevLune Studios',
  publisher: 'DevLune Studios',

  // ─── Canonical Base ────────────────────────────────────
  metadataBase: new URL(SITE_URL),

  // ─── Open Graph ─────────────────────────────────────────
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: SITE_URL,
    siteName: SITE_NAME,
    title: 'Voltex Notes — Open-Source Knowledge Base with Graph View & Cloud Sync',
    description: SITE_DESCRIPTION,
    // images auto-generated by app/opengraph-image.tsx
  },

  // ─── Twitter Card ───────────────────────────────────────
  twitter: {
    card: 'summary_large_image',
    title: 'Voltex Notes — Open-Source Knowledge Base',
    description: SITE_DESCRIPTION,
    // images auto-generated by app/twitter-image.tsx
  },

  // ─── Icons ──────────────────────────────────────────────
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '16x16 32x32', type: 'image/x-icon' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-touch-icon.png',
  },

  // ─── Manifest ───────────────────────────────────────────
  manifest: '/manifest.json',

  // ─── Robots ─────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // ─── Verification (add real tokens when ready) ──────────
  // verification: {
  //   google: 'your-google-site-verification',
  //   yandex: 'your-yandex-verification',
  // },

  // ─── Category ───────────────────────────────────────────
  category: 'productivity',

  // ─── Other ──────────────────────────────────────────────
  other: {
    'msapplication-TileColor': '#1e1e2e',
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#1e1e2e' },
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
  ],
  width: 'device-width',
  initialScale: 1,
  userScalable: true,
}

// ─── JSON-LD Structured Data ──────────────────────────────────────────────────
function JsonLd() {
  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebApplication',
        name: 'Voltex Notes',
        url: SITE_URL,
        description: SITE_DESCRIPTION,
        applicationCategory: 'ProductivityApplication',
        operatingSystem: 'Web',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
        author: {
          '@type': 'Organization',
          name: 'DevLune Studios',
          url: 'https://devlune.in',
          email: 'sidharth@devlune.in',
          logo: `${SITE_URL}/voltex-icon.svg`,
        },
        featureList: [
          'Markdown editing with live preview',
          'Bidirectional linking with wikilinks',
          'Interactive graph view',
          'Real-time cloud sync via Firebase',
          'Version history with diffs',
          'Plugin & theme marketplace',
          'Canvas / Excalidraw drawing',
          'Kanban boards',
          'Command palette',
          'Custom CSS theming',
        ],
      },
      {
        '@type': 'Organization',
        name: 'DevLune Studios',
        url: 'https://devlune.in',
        logo: `${SITE_URL}/voltex-icon.svg`,
        email: 'sidharth@devlune.in',
        sameAs: [
          'https://github.com/Dev-Lune',
          'https://www.linkedin.com/company/devluneorg',
        ],
      },
      {
        '@type': 'WebSite',
        name: 'Voltex Notes',
        url: SITE_URL,
        potentialAction: {
          '@type': 'SearchAction',
          target: { '@type': 'EntryPoint', urlTemplate: `${SITE_URL}/?q={search_term_string}` },
          'query-input': 'required name=search_term_string',
        },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Voltex Notes', item: SITE_URL },
        ],
      },
    ],
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
    />
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <JsonLd />
      </head>
      <body className="font-sans antialiased">
        {children}
        {process.env.NEXT_PUBLIC_VERCEL_ENV && <Analytics />}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-0JTRDFGX5J"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-0JTRDFGX5J');
          `}
        </Script>
      </body>
    </html>
  )
}
